### ISSUE TITLE
Error in running test programs

### ISSUE THREAD

**Issue by abhishek111226** [IntelLabs/Latte.py#1]
Hi, 
After installing latte.py, I tried to run tests.
However, I get following error for every test-case:

> E       NotImplementedError: SymbolRef(name='in_y', type=None)

> latte/analysis.py:80: NotImplementedError

It also prints AST that causes exception (during type inference).

Any clarifications in this regard would be of great help.

Thanking you.

**Comment by taknevski** [comment]
Hi Abhishek

Thank you, can you try running the following please:

python benchmarks/overfeat.py
python benchmarks/vgg.py
python benchmarks/alexnet.py
python examples/googlenet-v1/GoogLeNet_inference_2.py

and let me know if you face the same problem please?
Also can I know what machine you are running on and whether you have set your .ctree.cfg appropriately please?

Thanks,
Anand

**Comment by vandana96** [comment]
Hi,
After collaborating with Abhishek, this is the same error we are facing for the first three commands and we are facing the same issue.

We are running on x86_64 architecture (Ubuntu 14.04), 64 bit architecture.

The .ctree.cfg has been set appropriately with the following contents
[c]
CC = g++
CFLAGS = -O3 -std=c++11 -openmp -fPIC -mavx2 -mfma
LDFLAGS = -ltbb -I/opt/intel/mkl/include

OUTPUT OF python3 benchmarks/overfeat.py

$python3 benchmarks/overfeat.py
INFO:latte:========== Configuration ==========
INFO:latte:    march             = AVX-2
INFO:latte:    parallel_strategy = SIMPLE_LOOP
INFO:latte:    nthreads          = unspecified
INFO:latte:    codegen_strategy = AUTOVEC
INFO:latte:===================================
Benchmark Config
    batch_size = 64
Compiling...
INFO:latte:Initializing ensembles and synthesizing functions...
INFO:latte:    ensemble1 [shape=(8, 224, 224)]
INFO:latte:    ensemble2 [shape=(96, 54, 54)]
Hello SymbolRef(name='in_y', type=None)
AST that caused exception during type inference
void func(float* ensemble2value, float* ensemble2inputs, float* ensemble2weights) {
    for (int _neuron_index_0 = 0; _neuron_index_0 < 64; _neuron_index_0 += 1) {
        for (int _neuron_index_1_outer = 0; _neuron_index_1_outer < 12; _neuron_index_1_outer += 1) {
            for (int i_outer = 0; i_outer < 1; i_outer += 1) {
                for (int _neuron_index_2 = 0; _neuron_index_2 < 54; _neuron_index_2 += 1) {
                    for (int _neuron_index_3 = 0; _neuron_index_3 < 54; _neuron_index_3 += 1) {
                        for (long _neuron_index_1_inner = 0; _neuron_index_1_inner < 8; _neuron_index_1_inner += 1) {
                            
                            int ____temp___input_offset_1_outer = 0 / 8;
                            int _input_offset_1_outer = ____temp___input_offset_1_outer;

                            
                            int ____temp___input_offset_1_inner = 0 % 8;
                            int _input_offset_1_inner = ____temp___input_offset_1_inner;

                            
                            int ____temp__in_y = _neuron_index_2 * 4;
                            int in_y = ____temp__in_y;

                            
                            ____temp___input_offset_2 = in_y;
                            _input_offset_2 = ____temp___input_offset_2;

                            
                            ____temp__in_x = _neuron_index_3 * 4;
                            in_x = ____temp__in_x;

                            
                            ____temp___input_offset_3 = in_x;
                            _input_offset_3 = ____temp___input_offset_3;

                            for (int j = 0; j < 11; j += 1) {
                                for (int k = 0; k < 11; k += 1) {
                                    for (int i_inner = 0; i_inner < 8; i_inner += 1) {
                                        ensemble2value[_neuron_index_0][_neuron_index_1_outer][_neuron_index_2][_neuron_index_3][_neuron_index_1_inner] += ensemble2inputs[_neuron_index_0][(i_outer + _input_offset_1_outer)][(j * 1 + _input_offset_2)][(k * 1 + _input_offset_3)][(i_inner + _input_offset_1_inner)] * ensemble2weights[_neuron_index_1_outer][i_outer][j][k][_neuron_index_1_inner][i_inner];
                                    };
                                };
                            };
                        };
                    };
                };
            };
        };
    };
}
Traceback (most recent call last):
  File "benchmarks/overfeat.py", line 66, in <module>
    main()
  File "benchmarks/overfeat.py", line 39, in main
    net.compile()
  File "/home/vandana/Vandana/8thsem/IITH/downloads/latte-master/latte/core.py", line 349, in compile
    body, args = self._synthesize_ast(ensemble, neuron, "forward")
  File "/home/vandana/Vandana/8thsem/IITH/downloads/latte-master/latte/core.py", line 1248, in _synthesize_ast
    func_def = analyzer.type_infer(func_def)
  File "/home/vandana/Vandana/8thsem/IITH/downloads/latte-master/latte/analysis.py", line 80, in type_infer
    raise e
  File "/home/vandana/Vandana/8thsem/IITH/downloads/latte-master/latte/analysis.py", line 76, in type_infer
    return BasicTypeInference().visit(ast)
  File "/home/vandana/Vandana/8thsem/IITH/downloads/latte-master/latte/analysis.py", line 21, in visit
    node = super().visit(node)
  File "/usr/lib/python3.4/ast.py", line 245, in visit
    return visitor(node)
  File "/usr/lib/python3.4/ast.py", line 301, in generic_visit
    value = self.visit(value)
  File "/home/vandana/Vandana/8thsem/IITH/downloads/latte-master/latte/analysis.py", line 21, in visit
    node = super().visit(node)
  File "/usr/lib/python3.4/ast.py", line 245, in visit
    return visitor(node)
  File "/usr/lib/python3.4/ast.py", line 301, in generic_visit
    value = self.visit(value)
  File "/home/vandana/Vandana/8thsem/IITH/downloads/latte-master/latte/analysis.py", line 21, in visit
    node = super().visit(node)
  File "/usr/lib/python3.4/ast.py", line 245, in visit
    return visitor(node)
  File "/usr/lib/python3.4/ast.py", line 301, in generic_visit
    value = self.visit(value)
  File "/home/vandana/Vandana/8thsem/IITH/downloads/latte-master/latte/analysis.py", line 21, in visit
    node = super().visit(node)
  File "/usr/lib/python3.4/ast.py", line 245, in visit
    return visitor(node)
  File "/usr/lib/python3.4/ast.py", line 301, in generic_visit
    value = self.visit(value)
  File "/home/vandana/Vandana/8thsem/IITH/downloads/latte-master/latte/analysis.py", line 21, in visit
    node = super().visit(node)
  File "/usr/lib/python3.4/ast.py", line 245, in visit
    return visitor(node)
  File "/usr/lib/python3.4/ast.py", line 301, in generic_visit
    value = self.visit(value)
  File "/home/vandana/Vandana/8thsem/IITH/downloads/latte-master/latte/analysis.py", line 21, in visit
    node = super().visit(node)
  File "/usr/lib/python3.4/ast.py", line 245, in visit
    return visitor(node)
  File "/usr/lib/python3.4/ast.py", line 301, in generic_visit
    value = self.visit(value)
  File "/home/vandana/Vandana/8thsem/IITH/downloads/latte-master/latte/analysis.py", line 21, in visit
    node = super().visit(node)
  File "/usr/lib/python3.4/ast.py", line 245, in visit
    return visitor(node)
  File "/usr/lib/python3.4/ast.py", line 301, in generic_visit
    value = self.visit(value)
  File "/home/vandana/Vandana/8thsem/IITH/downloads/latte-master/latte/analysis.py", line 21, in visit
    node = super().visit(node)
  File "/usr/lib/python3.4/ast.py", line 245, in visit
    return visitor(node)
  File "/usr/lib/python3.4/ast.py", line 301, in generic_visit
    value = self.visit(value)
  File "/home/vandana/Vandana/8thsem/IITH/downloads/latte-master/latte/analysis.py", line 21, in visit
    node = super().visit(node)
  File "/usr/lib/python3.4/ast.py", line 245, in visit
    return visitor(node)
  File "/home/vandana/Vandana/8thsem/IITH/downloads/latte-master/latte/analysis.py", line 68, in visit_BinaryOp
    node.left.type = self._get_type(node.right)
  File "/home/vandana/Vandana/8thsem/IITH/downloads/latte-master/latte/analysis.py", line 55, in _get_type
    raise NotImplementedError(ast.dump(node))
NotImplementedError: SymbolRef(name='in_y', type=None)
vandana@vandana-Satellite-L740-X4210:~/Vandana/8thsem/IITH/downloads/latte-master$ 
vandana@vandana-Satellite-L740-X4210:~/Vandana/8thsem/IITH/downloads/latte-master$ python3 benchmarks/overfeat.py
INFO:latte:========== Configuration ==========
INFO:latte:    march             = AVX-2
INFO:latte:    parallel_strategy = SIMPLE_LOOP
INFO:latte:    nthreads          = unspecified
INFO:latte:    codegen_strategy = AUTOVEC
INFO:latte:===================================
Benchmark Config
    batch_size = 64
Compiling...
INFO:latte:Initializing ensembles and synthesizing functions...
INFO:latte:    ensemble1 [shape=(8, 224, 224)]
INFO:latte:    ensemble2 [shape=(96, 54, 54)]
Hello SymbolRef(name='in_y', type=None)
AST that caused exception during type inference
void func(float* ensemble2value, float* ensemble2inputs, float* ensemble2weights) {
    for (int _neuron_index_0 = 0; _neuron_index_0 < 64; _neuron_index_0 += 1) {
        for (int _neuron_index_1_outer = 0; _neuron_index_1_outer < 12; _neuron_index_1_outer += 1) {
            for (int i_outer = 0; i_outer < 1; i_outer += 1) {
                for (int _neuron_index_2 = 0; _neuron_index_2 < 54; _neuron_index_2 += 1) {
                    for (int _neuron_index_3 = 0; _neuron_index_3 < 54; _neuron_index_3 += 1) {
                        for (long _neuron_index_1_inner = 0; _neuron_index_1_inner < 8; _neuron_index_1_inner += 1) {
                            
                            int ____temp___input_offset_1_outer = 0 / 8;
                            int _input_offset_1_outer = ____temp___input_offset_1_outer;

                            
                            int ____temp___input_offset_1_inner = 0 % 8;
                            int _input_offset_1_inner = ____temp___input_offset_1_inner;

                            
                            int ____temp__in_y = _neuron_index_2 * 4;
                            int in_y = ____temp__in_y;

                            
                            ____temp___input_offset_2 = in_y;
                            _input_offset_2 = ____temp___input_offset_2;

                            
                            ____temp__in_x = _neuron_index_3 * 4;
                            in_x = ____temp__in_x;

                            
                            ____temp___input_offset_3 = in_x;
                            _input_offset_3 = ____temp___input_offset_3;

                            for (int j = 0; j < 11; j += 1) {
                                for (int k = 0; k < 11; k += 1) {
                                    for (int i_inner = 0; i_inner < 8; i_inner += 1) {
                                        ensemble2value[_neuron_index_0][_neuron_index_1_outer][_neuron_index_2][_neuron_index_3][_neuron_index_1_inner] += ensemble2inputs[_neuron_index_0][(i_outer + _input_offset_1_outer)][(j * 1 + _input_offset_2)][(k * 1 + _input_offset_3)][(i_inner + _input_offset_1_inner)] * ensemble2weights[_neuron_index_1_outer][i_outer][j][k][_neuron_index_1_inner][i_inner];
                                    };
                                };
                            };
                        };
                    };
                };
            };
        };
    };
}
Traceback (most recent call last):
  File "benchmarks/overfeat.py", line 66, in <module>
    main()
  File "benchmarks/overfeat.py", line 39, in main
    net.compile()
  File "/home/vandana/Vandana/8thsem/IITH/downloads/latte-master/latte/core.py", line 349, in compile
    body, args = self._synthesize_ast(ensemble, neuron, "forward")
  File "/home/vandana/Vandana/8thsem/IITH/downloads/latte-master/latte/core.py", line 1248, in _synthesize_ast
    func_def = analyzer.type_infer(func_def)
  File "/home/vandana/Vandana/8thsem/IITH/downloads/latte-master/latte/analysis.py", line 80, in type_infer
    raise e
  File "/home/vandana/Vandana/8thsem/IITH/downloads/latte-master/latte/analysis.py", line 76, in type_infer
    return BasicTypeInference().visit(ast)
  File "/home/vandana/Vandana/8thsem/IITH/downloads/latte-master/latte/analysis.py", line 21, in visit
    node = super().visit(node)
  File "/usr/lib/python3.4/ast.py", line 245, in visit
    return visitor(node)
  File "/usr/lib/python3.4/ast.py", line 301, in generic_visit
    value = self.visit(value)
  File "/home/vandana/Vandana/8thsem/IITH/downloads/latte-master/latte/analysis.py", line 21, in visit
    node = super().visit(node)
  File "/usr/lib/python3.4/ast.py", line 245, in visit
    return visitor(node)
  File "/usr/lib/python3.4/ast.py", line 301, in generic_visit
    value = self.visit(value)
  File "/home/vandana/Vandana/8thsem/IITH/downloads/latte-master/latte/analysis.py", line 21, in visit
    node = super().visit(node)
  File "/usr/lib/python3.4/ast.py", line 245, in visit
    return visitor(node)
  File "/usr/lib/python3.4/ast.py", line 301, in generic_visit
    value = self.visit(value)
  File "/home/vandana/Vandana/8thsem/IITH/downloads/latte-master/latte/analysis.py", line 21, in visit
    node = super().visit(node)
  File "/usr/lib/python3.4/ast.py", line 245, in visit
    return visitor(node)
  File "/usr/lib/python3.4/ast.py", line 301, in generic_visit
    value = self.visit(value)
  File "/home/vandana/Vandana/8thsem/IITH/downloads/latte-master/latte/analysis.py", line 21, in visit
    node = super().visit(node)
  File "/usr/lib/python3.4/ast.py", line 245, in visit
    return visitor(node)
  File "/usr/lib/python3.4/ast.py", line 301, in generic_visit
    value = self.visit(value)
  File "/home/vandana/Vandana/8thsem/IITH/downloads/latte-master/latte/analysis.py", line 21, in visit
    node = super().visit(node)
  File "/usr/lib/python3.4/ast.py", line 245, in visit
    return visitor(node)
  File "/usr/lib/python3.4/ast.py", line 301, in generic_visit
    value = self.visit(value)
  File "/home/vandana/Vandana/8thsem/IITH/downloads/latte-master/latte/analysis.py", line 21, in visit
    node = super().visit(node)
  File "/usr/lib/python3.4/ast.py", line 245, in visit
    return visitor(node)
  File "/usr/lib/python3.4/ast.py", line 301, in generic_visit
    value = self.visit(value)
  File "/home/vandana/Vandana/8thsem/IITH/downloads/latte-master/latte/analysis.py", line 21, in visit
    node = super().visit(node)
  File "/usr/lib/python3.4/ast.py", line 245, in visit
    return visitor(node)
  File "/usr/lib/python3.4/ast.py", line 301, in generic_visit
    value = self.visit(value)
  File "/home/vandana/Vandana/8thsem/IITH/downloads/latte-master/latte/analysis.py", line 21, in visit
    node = super().visit(node)
  File "/usr/lib/python3.4/ast.py", line 245, in visit
    return visitor(node)
  File "/home/vandana/Vandana/8thsem/IITH/downloads/latte-master/latte/analysis.py", line 68, in visit_BinaryOp
    node.left.type = self._get_type(node.right)
  File "/home/vandana/Vandana/8thsem/IITH/downloads/latte-master/latte/analysis.py", line 55, in _get_type
    raise NotImplementedError(ast.dump(node))
**NotImplementedError: SymbolRef(name='in_y', type=None)**

**Comment by taknevski** [comment]
Hi,
Do you have access to icc or icpc? If you do could you please check if that works ?

**Comment by taknevski** [comment]
Also please set you env variables as follows:

export LATTE_PARALLEL_STRATEGY=OPENMP
export LATTE_CODEGEN_STRATEGY=AUTOVEC
export LATTE_NUM_THREADS=88 #please adjust according to machine
export LATTE_MODE=RELEASE
export LATTE_PREFETCH_MODE=ON
export LATTE_TIMER=OFF
export LATTE_VEC_CONFIG=AVX-2
export LATTE_AUTO_FUSION=ON
export LATTE_SIMPLE_FUSION=ON
export LATTE_UNROLL=ON

**Comment by vandana96** [comment]
I currently dont have access to icc but will try in a few days.

I still face the same issue after setting the environment variables.

**Comment by taknevski** [comment]
I believe you might not be running the most recent version of the code based on your line numbers for core.py and analysis.py.. Maybe you could do a git pull again?

**Comment by taknevski** [comment]
I don't see 
func_def = analyzer.type_infer(func_def) 
on line 1248 of core.py for example..

**Comment by vandana96** [comment]
Hello,

I reinstalled latte by downloading the zip folder and I face the same error.

I have attached the output of running the test folder below (output.txt)

Command: python3 -m pytest test/
[output.txt](https://github.com/IntelLabs/Latte.py/files/1610622/output.txt)

The .ctree.cfg file has the following:
[c]
CC = g++
CFLAGS = -O3 -std=c++11 -openmp -fPIC -mavx2 -mfma
LDFLAGS = -ltbb -I/opt/intel/mkl/include

**Comment by taknevski** [comment]
I am able to run with icpc, currently gcc/g++ is not supported for latte
:

srun py.test test/test_concat.py
============================= test session starts ==============================
platform linux -- Python 3.5.3, pytest-2.9.2, py-1.4.31, pluggy-0.3.1
rootdir: /nfs_home/avenkat/important/Latte.py, inifile: 
collected 1 items
 
test/test_concat.py .
 
=========================== 1 passed in 9.92 seconds ===========================
.ctree.cfg:

[c]
CC = icpc
CFLAGS = -fPIC -O3 -std=c++11 -ansi-alias -march=core-avx2 -qopenmp

**Comment by taknevski** [comment]
maybe you can send me your latte zip archive and I can compare with my source..

**Comment by rajbarik** [comment]
This is a long time pending task!  We should support GCC by wrapping array
accesses in a macro. This can be done as part of code generation.

**Comment by taknevski** [comment]
Yes, but I don;t understand why analysis.py throws an error for Vandhana..

**Comment by taknevski** [comment]
gcc should not affect that right?

**Comment by rajbarik** [comment]
One of the error that Vandana reporting is this:

for (long _neuron_index_1_inner = 0; _neuron_index_1_inner < 8;
_neuron_index_1_inner += 1) { }

Type inferencing is failing on this for some reason. These should all be
integers not longs.

For GCC, do you know how to generate the code? I can send you a templated
code. Let me know.

**Comment by vandana96** [comment]
Hello,

I will try on icpc soon.

I have attached the latte zip file below.

Thanks.
[Latte.py-master.zip](https://github.com/IntelLabs/Latte.py/files/1618207/Latte.py-master.zip)

**Comment by vandana96** [comment]
Hello,

I tried it on icpc and it worked.

Thanks.

**Comment by abhishek111226** [comment]
Hi Thanks for your help.
I am closing this issue.

Best Regards,
